#!/usr/bin/env node
// Prisma generator that writes the full DMMF datamodel (which the generated client
// does not ship at runtime) to a TypeScript module used by the generic CRUD layer.
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import generatorHelper from '@prisma/generator-helper'

const { generatorHandler } = generatorHelper

generatorHandler({
  onManifest() {
    return { prettyName: 'Admin metadata', defaultOutput: '../src/generated/admin-meta.ts' }
  },
  async onGenerate(options) {
    const { models, enums } = options.dmmf.datamodel
    const datamodel = {
      models: models.map((model) => ({
        name: model.name,
        dbName: model.dbName,
        fields: model.fields.map((field) => ({
          name: field.name,
          kind: field.kind,
          type: field.type,
          nativeType: field.nativeType ? field.nativeType[0] : null,
          isList: field.isList,
          isRequired: field.isRequired,
          isId: field.isId,
          isUnique: field.isUnique,
          isReadOnly: field.isReadOnly,
          isUpdatedAt: field.isUpdatedAt ?? false,
          hasDefaultValue: field.hasDefaultValue,
          relationName: field.relationName ?? null,
          relationFromFields: field.relationFromFields ?? [],
          relationToFields: field.relationToFields ?? [],
        })),
      })),
      enums: Object.fromEntries(enums.map((e) => [e.name, e.values.map((v) => v.name)])),
    }

    const outputFile = options.generator.output?.value
    if (!outputFile) throw new Error('admin-meta generator: missing output')
    await mkdir(path.dirname(outputFile), { recursive: true })
    await writeFile(
      outputFile,
      `// Generated by prisma/generators/admin-meta.mjs. Do not edit.\n` +
        `import type { Datamodel } from '../crud/datamodel.js'\n\n` +
        `export const datamodel: Datamodel = ${JSON.stringify(datamodel, null, 2)}\n`,
    )
  },
})
